baseURL = 'https://site-consultoria-pd8r.vercel.app/'
languageCode = 'pt-br'
title = 'Henrique Oliver | Finanças e Governança'
theme = 'ananke'

[params]
  description = "Especialista em Administração Pública e Gestão de TI"
  custom_css = []

[module]
  [[module.mounts]]
    source = 'content'
    target = 'content'
  [[module.mounts]]
    source = 'themes/ananke'
    target = 'themes/ananke'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'themes/ananke/assets'
    target = 'assets'

[build]
  writeStats = true
