baseURL = "https://site-consultoria-pd8r.vercel.app/"
languageCode = "pt-br"
title = "Henrique Oliver"
theme = "meutema"

[params]
  description = "Especialista em Administração Pública e Tecnologia da Informação."
  featured_image = "/images/capa-site.jpg"
  favicon = "/favicon.svg"
  body_classes = "avenir bg-near-white"

  [[params.social]]
    name = "LinkedIn"
    icon = "linkedin"
    url = "https://www.linkedin.com/in/henriqueoliver/"

  [[params.social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/henriqueoliver"

[menu]
  [[menu.main]]
    identifier = "sobre"
    name = "Sobre Henrique Oliver"
    url = "/sobre/"
    weight = 5

  [[menu.main]]
    identifier = "servicos"
    name = "Serviços & Projetos"
    url = "/#servicos"
    weight = 10

  [[menu.main]]
    identifier = "portfolios"
    name = "Portfólio & Cases"
    url = "/projetos/"
    weight = 15

  [[menu.main]]
    identifier = "contato"
    name = "Falar com Agente IA"
    url = "/contato/"
    weight = 20