baseURL = 'https://site-consultoria-pd8r.vercel.app/'
languageCode = 'pt-br'
title = 'Henrique Oliver | Finanças e Governança'
theme = 'meutema'

[params]
  description = "Especialista em Administração Pública e Gestão de TI"
  custom_css = []
