baseURL = 'https://henriqueoliver.adm.br/'
languageCode = 'pt-br'
title = 'Henrique Oliver | Finanças e Governança'
theme = 'ananke'

[params]
  description = "Especialista em Administração Pública e Gestão de TI"

# Força o Hugo a reconhecer a pasta themes local
[module]
  replacements = "github.com/theNewDynamic/gohugo-theme-ananke -> themes/ananke"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
